map_type: costmap

obstacle_range: 3.1
raytrace_range: 4.0
inflation_radius: 0.5

transform_tolerance: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
